name: Update Version and Changelog

on:
  push:
    branches:
      - yx
    # 仅在提交消息包含 feat 时触发
    types:
      - committed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install standard-version
        run: |
          npm install standard-version --save-dev

      # 根据提交类型自动更新版本号和 CHANGELOG.md
      - name: Update version and changelog
        if: contains(github.event.head_commit.message, 'feat') # 仅在 feat 类型提交时执行
        run: |
          npx standard-version --release-as minor  # 更新版本为次版本
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): update version and changelog"
          git push --follow-tags
