name: Update Changelog

on:
  push:
    branches:
      - yx  # 推送到 yx 分支时触发

jobs:
  changelog:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 指定 Node.js 版本

      - name: Install dependencies
        run: |
          npm install -g standard-version
          npm install -g conventional-changelog-cli

      - name: Generate changelog
        run: |
          standard-version
          conventional-changelog -p angular -i CHANGELOG.md -s --template .github/workflows/changelog.hbs

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push

      - name: Tag and push
        run: |
          VERSION=$(jq -r '.version' package.json)
          DATE=$(date +'%Y.%m.%d')
          FULL_VERSION="v$VERSION-$DATE"
          git tag "$FULL_VERSION"
          git push origin "$FULL_VERSION"
