name: Update Changelog

on:
  push:
    branches:
      - yx  # 推送到 yx 分支时触发

jobs:
  changelog:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出你的代码

      - name: Set up Node.js environment
        uses: actions/setup-node@v3  # 设置 Node.js 环境
        with:
          node-version: '18'  # 指定 Node.js 版本

      - name: Install dependencies
        run: |
          npm install auto-changelog --global  # 全局安装 auto-changelog

      - name: Generate changelog
        run: |
          auto-changelog -p  # 使用 auto-changelog 生成 CHANGELOG.md 文件

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"  # 配置 Git 用户名
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # 配置 Git 用户邮箱
          git add CHANGELOG.md  # 添加生成的 changelog 文件
          git commit -m "chore: update changelog" || echo "No changes to commit"  # 提交更改
          git push  # 推送到远程仓库
